### ISSUE TITLE
UI doesn't work on Ubuntu Firefox 128.0.3

### ISSUE THREAD

**Issue by Ktmi** [kytos-ng/ui#75]
I've been trying to test some things in the UI with firefox, but it doesn't seem to work correctly, as many of the buttons and forms don't work. I originally thought it was an issue with specific NApps, but after testing things, it appears to be a compatibility issue between kytos UI and the browser.

Previous issues:
kytos-ng/sdntrace#91
kytos-ng/sdntrace_cp#121

**Comment by viniarck** [comment]
Temporarily setting the label `2024.1` for this to be on our radar to be looked into before we ship the release and make a decision.

**Comment by viniarck** [comment]
Assigning Rogerio to this issue, since he's already helping with it. Thanks, guys.

**Comment by Ktmi** [comment]
@rmotitsuki Requested the full errors on some things, so here they are:
Message 1:
```
TypeError: this.$kytos.eventBus is undefined
    mounted build.js line 2 > Function:52
    VueJS 12
        Wt
        an
        insert
        x
        Wr
        _update
        c
        get
        run
        gn
        ce
        Xt
vue.esm.js:1906:12
    VueJS 15
        Zt
        Yt
        Ht
        Wt
        an
        insert
        x
        Wr
        _update
        c
        get
        run
        gn
        ce
        Xt

```

Message 2:

```
TypeError: this.$kytos.toRaw is not a function
    filtered_EVCData build.js line 2 > Function:234
    VueJS 3
        get
        evaluate
        wn
    anonymous build.js line 2 > Function:3
    VueJS 20
        _render
        c
        get
        mn
        mount
        $mount
        $mount
        init
        u
        u
        k
        k
        Wr
        _update
        c
        get
        run
        gn
        ce
        Xt
vue.esm.js:1906:12
    VueJS 23
        Zt
        Yt
        Ht
        _render
        c
        get
        mn
        mount
        $mount
        $mount
        init
        u
        u
        k
        k
        Wr
        _update
        c
        get
        run
        gn
        ce
        Xt

```

**Comment by rmotitsuki** [comment]
We found out that the problem was browser cache.
A proposed fix would be to leave it as nocache or force the cache to reload.
